name: Test Kotlin C Interop

on:
  push:
    branches: [ main ]
    paths: 
      - 'kotlin-cinterop/**/*'
  pull_request:
    branches: [ main ]
    paths: 
      - 'kotlin-cinterop/**/*'

defaults:
  run:
    working-directory: kotlin-cinterop

jobs:
  testOnUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build library
        run: |
          ./gradlew myplugin:createReleaseLinux
          find myplugin/build/lib
      - name: Build
        run: ./gradlew build
      - name: Run executable
        run: ./gradlew runReleaseExecutableLinuxX64

  testOnMacOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build library
        run: |
          ./gradlew myplugin:createReleaseMacos
          find myplugin/build/lib
      - name: Build
        run: ./gradlew linkReleaseExecutableMacosX64
      - name: Run executable
        run: ./gradlew runReleaseExecutableMacosX64

  testOnWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build library
        run: |
          .\gradlew myplugin:createReleaseWindows
          Get-ChildItem -r myplugin\build
      - name: Build
        run: .\gradlew linkReleaseExecutableWindowsX64
      - name: Run executable
        run: .\gradlew runReleaseExecutableWindowsX64
